openapi: 3.0.3
info:
  title: Swagger
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://commerce-project-2-nine.vercel.app
  - url: http://localhost:3000


# ---------------product user ----------
tags:
  - name: products
    description: Sản phẩm phía người dùng
  - name: categories
    description: Danh mục sản phẩm phía người dùng
  - name: users
paths:
  /products:
    get:
      tags:
        - products
      summary: Lấy sản phẩm
      operationId: getProductUser
      parameters:
        - name: searchKey
          in: query
          required: false
          schema:
            type: string
          description: Nhập từ tìm kiếm - tìm theo tiêu đề
        - name: sortKey
          in: query
          required: false
          schema:
            type: string
            enum: [product_title, price_unit]
          description: Field để sắp xếp
        - name: sortValue
          in: query
          required: false
          schema:
            type: string
            enum: [ASC, DESC]
          description: Sắp xếp tăng || Giảm
        - name: fromPrice
          in: query
          required: false
          schema:
            type: integer
            format: int64
          description: Giá trị tìm kiếm tiền từ
        - name: toPrice
          in: query
          required: false
          schema:
            type: integer
            format: int64
          description: Giá trị tìm kiếm tiền đến
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: Page
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Số lượng sản phẩm mỗi page
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/GetProduct'
                  totalPage:
                    type: integer
                    example: 1
                  pageNow:
                    type: integer
                    example: 1
        "400":
          description: Lỗi

  /products/like/{type}/{productId}:
    patch:
      tags:
        - products
      summary: Sản phẩm yêu thích (like)
      description: ''
      operationId: likeProduct
      security:
        - accessToken: []
      parameters:
        - name: type
          in: path
          description: type like (yes || no)
          required: true
          schema:
            type: string
        - name: productId
          in: path
          description: Id sản phẩm
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Thành công
        '400':
          description: Invalid input
        '401':
          description: Token không hợp lệ
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 401
                  message:
                    type: string
                    example: Invalid token. Access denied.

# ---------------end product user ----------



# --------------- category user ----------  
  /categories:
    get:
      tags:
        - categories
      summary: Lấy danh mục sản phẩm
      operationId: getCategoriesUser
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    items:
                      $ref: '#/components/schemas/GetCategory'
                  message:
                    type: string
                    example: "load dữ liệu thành công"
        "400":
          description: Lỗi lấy danh sách sản phẩm

# --------------- end category user ----------

# ----------- user --------
  /user/login:
    post: 
      tags: 
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "nguyenvanchien"
                password:
                  type: string
                  example: "123"
      responses: 
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  accessToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsX2lkIjoxMSwiaWF0IjoxNzI4Mzc2NTUwLCJleHAiOjE3Mjg0NjI5NTB9.Di-pZAyVdR5ZVxgFkg4w4q4GH9RpGySwV0GSZhUDxrI
                  refreshToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsX2lkIjoxMSwiaWF0IjoxNzI4Mzc2NTUwLCJleHAiOjE3Mjg5ODEzNTB9.4xHYy-GYH7KIyUVCoqDRPS5laFlk2jtq7yvflfAqQeM
        '401':
          description: Tài Khoản hoạt động hoặc không hợp lệ
        '402':
          description: Mật khẩu không đúng
        '400': 
          description: Login lỗi
      
  /user/logout:
    post: 
      tags: 
        - users
      operationId: logout
      security:
        - accessToken: []
      parameters:
      - name: accessToken
        in: header
        description: "Access token for authentication"
        required: true
        schema:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsX2lkIjoxMSwiaWF0IjoxNzI4Mzc2NTUwLCJleHAiOjE3Mjg0NjI5NTB9.Di-pZAyVdR5ZVxgFkg4w4q4GH9RpGySwV0GSZhUDxrI
      - name: refreshToken
        in: header
        description: "Refresh token for session management"
        required: true
        schema:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsX2lkIjoxMSwiaWF0IjoxNzI4Mzc2NTUwLCJleHAiOjE3Mjg5ODEzNTB9.4xHYy-GYH7KIyUVCoqDRPS5laFlk2jtq7yvflfAqQeM
      responses: 
        '200':
          description: "User logged out successfully."
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "User logged out successfully."
        '400':
          description: "Error during logout."
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Error - logout"
        '401':
          description: Tài Khoản hoạt động hoặc không hợp lệ 
      

# ----------- end user --------


components:
  schemas:
    GetProduct:
      type: object
      properties:
        product_id:
          type: integer
          example: 6
        category_id:
          type: integer
          example: 11
        product_title:
          type: string
          example: "Điện thoại Samsung Galaxy Z Fold6 5G 12GB/256GB"
        product_desc:
          type: string
          nullable: true
          example: null
        image_url:
          type: string
          example: "https://cdn.tgdd.vn/Products/Images/42/320721/samsung-galaxy-z-fold6-xam-12-750x500.jpg"
        price_unit:
          type: integer
          example: 42200000
        quantity:
          type: integer
          example: 50
        slug:
          type: string
          example: "dien-thoai-samsung-galaxy-z-fold6"
        discount:
          type: integer
          example: 15
        newPrice:
          type: string
          example: "35870000"

    GetCategory:
      type: object
      properties:
        category_id:
          type: integer
          example: 11
        parent_category_id:
          type: integer
          nullable: true
          example: null
        category_title:
          type: string
          example: "Electronics"
        image_url:
          type: string
          example: "https://ecelectronics.com/wp-content/uploads/2020/04/Modern-Electronics-EC-.jpg"
        children:
          type: array
          items:
            $ref: '#/components/schemas/GetCategory'

  securitySchemes:
    accessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT  # Có thể là tùy chỉnh, ví dụ JWT, OAuth, v.v.